### ISSUE TITLE
File-scoped namespace

### ISSUE THREAD

**Issue by gptucci** [raffaeler/SpeedyGenerators#3]
Hi
All works fine but if I try to use it with namespace definition "file-scoped" (c# 10) I get an error.
Tnx

**Comment by raffaeler** [comment]
Hi @gptucci this is by design when combining C#10 and source generators:
- file scoped classes can be `partial` but all the partial classes must be defined in the same source file
- source generators are not allowed to modify the code edited from the users and need to create a different file.

Because of this, source generators cannot extend file scoped classes.

Thanks for your investigation!
